### ISSUE TITLE
Guide does not work with latest Istio release (1.1.0)

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/guide-istio-intro#49]
In the Istio guide we direct people to download an Istio release, but not which release.  Given Istio releases seem to break backwards compatibility we probably need to:
1.  Be prescriptive as to which release to use (urgent)
2. Update the guide to work with the latest release (less urgent)

This issue could be split into two....

**Comment by gkwan-ibm** [comment]
- investigating the different from Istio 1.1.0

**Comment by gkwan-ibm** [comment]
- identified the difference between 1.0.6 and 1.1.0
- need to find out how Windows to apply those istio yaml files

**Comment by andrewdes** [comment]
Issue arises in the **Deploying Istio** section when trying to deploy the Istio custom resource definitions: `kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml`. 

In Istio 1.1.0, the `crds.yaml` file does not exist in the directory specified above. According to the [Istio documentation](https://istio.io/docs/setup/kubernetes/install/kubernetes/), you have to deploy the custom resource definition files in the `install/kubernetes/helm/istio-init/files` directory. Since there are several files, a for loop is used:
```
for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done
```
and the Windows equivalent would be: 
```
FOR %i in (install\kubernetes\helm\istio-init\files\crd*yaml) DO kubectl apply -f %i
```

Also, in the **Tearing down your environment** section, the command for deleting Istio resources from the cluster would not to be modified:
```
for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl delete -f $i; done
```
