### ISSUE TITLE
Guide expected output does not match mine

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/guide-istio-intro#75]
What the guide asked:

![image](https://user-images.githubusercontent.com/26514093/63468095-fe948300-c434-11e9-835a-fad6b80f5bb6.png)

My terminal output after running the curl command:

![image](https://user-images.githubusercontent.com/26514093/63468035-cc832100-c434-11e9-850e-a5a41b1fa875.png)

What the guide stated the output would be:

![image](https://user-images.githubusercontent.com/26514093/63468072-f1779400-c434-11e9-90ea-ddd86951a464.png)

Therefore it doesn't pass the endpoint tests:

![image](https://user-images.githubusercontent.com/26514093/63468553-305a1980-c436-11e9-94eb-87ce9b970eaa.png)

**Comment by gkwan-ibm** [comment]
fixed by
- https://github.com/OpenLiberty/guide-istio-intro/commit/cdf33f0d3a393de082a3d99a544839f9e73a57fc
- https://github.com/OpenLiberty/guide-istio-intro/commit/9b3c8c6b55cbab2c1a56a401882d195731566758
- https://github.com/OpenLiberty/guide-istio-intro/commit/f7a19027ec32a27b39094a16434954688529bbde
- https://github.com/OpenLiberty/guide-istio-intro/commit/fd2fa9776ae41012fb15343cdc87663197e87d69
